baseURL = "https://runborg.github.io/cookbook/"
languageCode = "en-us"
title = "Family Cookbook"
theme = "congo"  # Replace with your theme if you use one
enableGitInfo = true

[params]
  description = "A collection of our family's treasured recipes"
  showSearch = true  # Enable search if supported by theme
  primaryColor = "#FF5733" # Customize this as you like
  secondaryColor = "#333333" # Customize this as you like
  search = true # Enable search
  mainSections = ["recipes"] # Used to create a section for recipes

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 3

[outputs]
  home = ["HTML", "RSS", "JSON"]  # If you want to enable JSON for search

[permalinks]
  recipes = "/:title/"

[taxonomies]
  category = "categories"

[[params.menu]]
  name = "Recipes"
  url = "/recipes/"

